query {
	Posts {
		id
		title
		description
		createDate
		author
	}
}

mutation {
	createPost(
		title: "Mi primer Post"
		description: "en mi primer post tengo que la vida no es facil"
		createDate: "25-09-2019"
		author: "Jesus GIlbert"
	) {
		id
		title
		description
		createDate
		author
	}
}

mutation {
	updatePost(
		id: 2
		title: "Mi segundo Post"
		description: "en mi primer post tengo que la vida no es facil"
		createDate: "26-09-2019"
		author: "Jesus GIlbert"
	)
}

mutation {
	deletePost(id: 1)
}
