type BookAuthor {
	bookId: ID!
	authorId: ID!
}

extend type Query {
	book_authors: [BookAuthor!]!
	book_author(bookId: ID!): [BookAuthor!]!
	author_book(authorId: ID!): [BookAuthor!]!
}

extend type Mutation {
	setBookAuthor(bookId: ID!, authorIds: [ID!]!): Message!
}
