type Book {
	id: ID!
	title: String!
	desc: String
	authors: [Author]
	publisher: Publisher
}

type Query {
	books: [Book!]!
	book(id: ID!): Book!
}

extend type Mutation {
	add_book(book: BookInput!): Message!
	edit_book(id: ID!, book: BookInput!): Message!
	delete_book(id: ID!): Message!
}

input BookInput {
	title: String
	authors: [ID!]
	publisher: ID!
}
